#------------------------------------------------------------
# Makefile
#------------------------------------------------------------
slnFile   = XG3DConverter.sln
outputDir = ./project/bin/Release
binFiles  = $(outputDir)/XG3DConverter.exe

#------------------------------------------------------------
projectRoot = ../..
include $(projectRoot)/PublishTool/MSBuildRule.mk

#------------------------------------------------------------
# EOF
