#------------------------------------------------------------
# Makefile
#------------------------------------------------------------
slnFile   = DAEConverter.sln
outputDir = ./project/bin/Release
binFiles  = $(outputDir)/DAEConverter.exe
  
#------------------------------------------------------------
projectRoot = ../..
include $(projectRoot)/PublishTool/MSBuildRule.mk

#------------------------------------------------------------
# EOF
