#------------------------------------------------------------
# Makefile
#------------------------------------------------------------
slnFile   = TGAConverter.sln
outputDir = ./project/bin/Release
binFiles  = $(outputDir)/TGAConverter.exe
  
#------------------------------------------------------------
projectRoot = ../..
include $(projectRoot)/PublishTool/MSBuildRule.mk

#------------------------------------------------------------
# EOF
