#------------------------------------------------------------
# Makefile
#------------------------------------------------------------
subDirs = \
  Collada141 \
  DAEConverter \
  TGAConverter \
  XDataConverter \
  XG3DConverter \
  XG3DDLL \
  
#------------------------------------------------------------
projectRoot = ..
include $(projectRoot)/PublishTool/SubDirRule.mk

#------------------------------------------------------------
# EOF
