#------------------------------------------------------------
# Makefile
#------------------------------------------------------------
slnFile   = XG3DDLL.sln
outputDir = ./project/bin/Release
binFiles  = \
  $(outputDir)/CrossFramework.XG3D.dll \
  $(outputDir)/CrossFramework.XG3D.XTEX.xsd \
  $(outputDir)/CrossFramework.XG3D.XMDL.xsd \
  
dllFiles  = \
  $(outputDir)/CrossFramework.XG3D.dll \
  $(outputDir)/CrossFramework.XG3D.xml \
  $(outputDir)/CrossFramework.XG3D.XTEX.xsd \
  $(outputDir)/CrossFramework.XG3D.XMDL.xsd \
  
#------------------------------------------------------------
projectRoot = ../..
include $(projectRoot)/PublishTool/MSBuildRule.mk

#------------------------------------------------------------
# EOF
