#------------------------------------------------------------
# Makefile
#------------------------------------------------------------
slnFile   = Collada141.sln
outputDir = ./project/bin/Release
binFiles  = \
  $(outputDir)/Collada141.dll \
  
#------------------------------------------------------------
projectRoot = ../..
include $(projectRoot)/PublishTool/MSBuildRule.mk

#------------------------------------------------------------
# EOF
